export const BUSINESS_LIMITS = {
  maxLevel: 5,
  upgradeConditionGain: 12,
};

const BUSINESS_ASSET_BASE = "./assets/businesses";

export const BUSINESS_TEMPLATES = [
  {
    id: "BUS_RU_MOS_BIRYULYOVO_SHAWARMA_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Бирюлёво Западное",
    address: "Булатниковский проезд, 3",
    type: "food_kiosk",
    scale: "micro",
    name: "Шаурма у станции",
    brand: "Local Street Food",
    buyPrice: 3500,
    dailyRevenue: 180,
    dailyExpenses: 80,
    condition: 42,
    staffSlots: 1,
    risk: 10,
  },
  {
    id: "BUS_RU_MOS_KAPOTNYA_TIRE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Капотня",
    address: "1-й квартал Капотни, 14",
    type: "auto_service",
    scale: "micro",
    name: "Шиномонтаж у промзоны",
    brand: "Local Auto Service",
    buyPrice: 5200,
    dailyRevenue: 240,
    dailyExpenses: 110,
    condition: 38,
    staffSlots: 2,
    risk: 12,
  },
  {
    id: "BUS_RU_MOS_NEKRASOVKA_COFFEE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Некрасовка",
    address: "Рождественская улица, 31",
    type: "coffee_point",
    scale: "small",
    name: "Кофе навынос",
    brand: "Local Coffee Point",
    buyPrice: 7000,
    dailyRevenue: 320,
    dailyExpenses: 145,
    condition: 56,
    staffSlots: 2,
    risk: 7,
  },
  {
    id: "BUS_RU_MOS_BUTOVO_MINI_MARKET_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Южное Бутово",
    address: "Скобелевская улица, 23",
    type: "mini_market",
    scale: "small",
    name: "Мини-маркет у дома",
    brand: "Local Market",
    buyPrice: 11000,
    dailyRevenue: 460,
    dailyExpenses: 240,
    condition: 52,
    staffSlots: 3,
    risk: 8,
  },
  {
    id: "BUS_RU_MOS_CHERTANOVO_BARBER_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Чертаново Центральное",
    address: "Кировоградская улица, 38",
    type: "barbershop",
    scale: "small",
    name: "Барбершоп у метро",
    brand: "Local Barber",
    buyPrice: 14500,
    dailyRevenue: 520,
    dailyExpenses: 260,
    condition: 60,
    staffSlots: 3,
    risk: 6,
  },
  {
    id: "BUS_RU_MOS_MITINO_OZON_POINT_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Митино",
    address: "Митинская улица, 40",
    type: "pickup_point",
    scale: "small",
    name: "Ozon Point",
    brand: "Ozon",
    buyPrice: 16000,
    dailyRevenue: 610,
    dailyExpenses: 330,
    condition: 66,
    staffSlots: 3,
    risk: 5,
  },
  {
    id: "BUS_RU_MOS_MITINO_WB_POINT_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Митино",
    address: "Пятницкое шоссе, 37",
    type: "pickup_point",
    scale: "small",
    name: "Wildberries Point",
    brand: "Wildberries",
    buyPrice: 16500,
    dailyRevenue: 630,
    dailyExpenses: 345,
    condition: 64,
    staffSlots: 3,
    risk: 5,
  },
  {
    id: "BUS_RU_MOS_CHERTANOVO_FITNESS_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Чертаново Центральное",
    address: "Днепропетровская улица, 16",
    type: "gym",
    scale: "small",
    name: "Подвальный зал единоборств",
    brand: "Local Fight Gym",
    buyPrice: 22000,
    dailyRevenue: 760,
    dailyExpenses: 410,
    condition: 49,
    staffSlots: 4,
    risk: 11,
  },
  {
    id: "BUS_RU_MOS_DANILOVSKY_CARWASH_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Даниловский",
    address: "Автозаводская улица, 19",
    type: "car_wash",
    scale: "medium",
    name: "Автомойка у ТТК",
    brand: "Local Car Wash",
    buyPrice: 28000,
    dailyRevenue: 980,
    dailyExpenses: 520,
    condition: 58,
    staffSlots: 5,
    risk: 10,
  },
  {
    id: "BUS_RU_MOS_BUTOVO_PYATEROCHKA_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Южное Бутово",
    address: "улица Адмирала Лазарева, 45",
    type: "grocery_store",
    scale: "medium",
    name: "Пятёрочка — районная точка",
    brand: "Пятёрочка",
    buyPrice: 36000,
    dailyRevenue: 1280,
    dailyExpenses: 760,
    condition: 70,
    staffSlots: 7,
    risk: 6,
  },
  {
    id: "BUS_RU_MOS_NEKRASOVKA_MAGNIT_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Некрасовка",
    address: "улица Недорубова, 10",
    type: "grocery_store",
    scale: "medium",
    name: "Магнит — районная точка",
    brand: "Магнит",
    buyPrice: 38000,
    dailyRevenue: 1340,
    dailyExpenses: 800,
    condition: 68,
    staffSlots: 7,
    risk: 6,
  },
  {
    id: "BUS_RU_MOS_CHERTANOVO_VKUSNO_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Чертаново Центральное",
    address: "Кировоградская улица, 13А",
    type: "fast_food",
    scale: "medium",
    name: "Вкусно — и точка, районная франшиза",
    brand: "Вкусно — и точка",
    buyPrice: 48000,
    dailyRevenue: 1750,
    dailyExpenses: 1060,
    condition: 74,
    staffSlots: 10,
    risk: 7,
  },
  {
    id: "BUS_RU_MOS_DANILOVSKY_CAFE_CHAIN_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Даниловский",
    address: "улица Ленинская Слобода, 26",
    type: "cafe_chain",
    scale: "medium",
    name: "Сетевая кофейня",
    brand: "Moscow Coffee Group",
    buyPrice: 62000,
    dailyRevenue: 2100,
    dailyExpenses: 1280,
    condition: 76,
    staffSlots: 10,
    risk: 6,
  },
  {
    id: "BUS_RU_MOS_DANILOVSKY_RESTAURANT_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Даниловский",
    address: "Дербеневская набережная, 7",
    type: "restaurant",
    scale: "medium",
    name: "Гриль-ресторан у набережной",
    brand: "Local Restaurant",
    buyPrice: 78000,
    dailyRevenue: 2600,
    dailyExpenses: 1620,
    condition: 72,
    staffSlots: 12,
    risk: 8,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_BAR_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "улица 1905 года, 10",
    type: "bar",
    scale: "medium",
    name: "Бар на Пресне",
    brand: "Local Bar",
    buyPrice: 90000,
    dailyRevenue: 3200,
    dailyExpenses: 2050,
    condition: 67,
    staffSlots: 12,
    risk: 14,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_BOUTIQUE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Пресненская набережная, 12",
    type: "retail_boutique",
    scale: "upper_medium",
    name: "Бутик в деловом центре",
    brand: "City Retail",
    buyPrice: 120000,
    dailyRevenue: 3900,
    dailyExpenses: 2500,
    condition: 81,
    staffSlots: 9,
    risk: 7,
  },
  {
    id: "BUS_RU_MOS_KHAMOVNIKI_CLINIC_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Хамовники",
    address: "Комсомольский проспект, 32",
    type: "private_clinic",
    scale: "upper_medium",
    name: "Частная клиника",
    brand: "Private Medical Group",
    buyPrice: 180000,
    dailyRevenue: 5600,
    dailyExpenses: 3700,
    condition: 85,
    staffSlots: 18,
    risk: 8,
  },
  {
    id: "BUS_RU_MOS_KHAMOVNIKI_FITNESS_PREMIUM_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Хамовники",
    address: "Усачёва улица, 11",
    type: "premium_gym",
    scale: "upper_medium",
    name: "Премиальный фитнес-клуб",
    brand: "Premium Fitness",
    buyPrice: 220000,
    dailyRevenue: 6800,
    dailyExpenses: 4300,
    condition: 88,
    staffSlots: 22,
    risk: 8,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_OFFICE_RENT_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Пресненская набережная, 8",
    type: "office_rent",
    scale: "large",
    name: "Офисный этаж в Москва-Сити",
    brand: "Moscow City Office",
    buyPrice: 350000,
    dailyRevenue: 9500,
    dailyExpenses: 6200,
    condition: 84,
    staffSlots: 8,
    risk: 6,
  },
  {
    id: "BUS_RU_MOS_DANILOVSKY_LOGISTICS_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Даниловский",
    address: "Автозаводская улица, 25",
    type: "logistics_hub",
    scale: "large",
    name: "Логистический склад",
    brand: "City Logistics",
    buyPrice: 420000,
    dailyRevenue: 11200,
    dailyExpenses: 7300,
    condition: 72,
    staffSlots: 32,
    risk: 12,
  },
  {
    id: "BUS_RU_MOS_MITINO_DATA_CENTER_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Митино",
    address: "Пятницкое шоссе, 52",
    type: "data_center",
    scale: "large",
    name: "Дата-центр на северо-западе",
    brand: "DataLine-inspired DC",
    buyPrice: 620000,
    dailyRevenue: 15400,
    dailyExpenses: 9800,
    condition: 78,
    staffSlots: 18,
    risk: 9,
  },
  {
    id: "BUS_RU_MOS_KHAMOVNIKI_HOTEL_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Хамовники",
    address: "Остоженка, 27",
    type: "boutique_hotel",
    scale: "large",
    name: "Бутик-отель в центре",
    brand: "Moscow Boutique Hotel",
    buyPrice: 750000,
    dailyRevenue: 18100,
    dailyExpenses: 11600,
    condition: 86,
    staffSlots: 28,
    risk: 10,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_BANK_BRANCH_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Пресненская набережная, 10",
    type: "bank_branch",
    scale: "large",
    name: "Сбер Плаза",
    brand: "Сбер",
    buyPrice: 900000,
    dailyRevenue: 22000,
    dailyExpenses: 14500,
    condition: 90,
    staffSlots: 20,
    risk: 5,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_YANDEX_OFFICE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "улица Льва Толстого, 16",
    type: "tech_office",
    scale: "corporate",
    name: "Яндекс Кампус",
    brand: "Яндекс",
    buyPrice: 1400000,
    dailyRevenue: 34000,
    dailyExpenses: 23000,
    condition: 92,
    staffSlots: 45,
    risk: 7,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_TBANK_OFFICE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Грузинский Вал, 11",
    type: "fintech_office",
    scale: "corporate",
    name: "Т-Банк Центр",
    brand: "Т-Банк",
    buyPrice: 1550000,
    dailyRevenue: 38000,
    dailyExpenses: 25500,
    condition: 91,
    staffSlots: 42,
    risk: 7,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_OZON_HQ_STAKE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Пресненская набережная, 6",
    type: "ecommerce_office",
    scale: "corporate",
    name: "Ozon Tech Hub",
    brand: "Ozon",
    buyPrice: 1800000,
    dailyRevenue: 43000,
    dailyExpenses: 29200,
    condition: 89,
    staffSlots: 52,
    risk: 8,
  },
  {
    id: "BUS_RU_MOS_KHAMOVNIKI_LUXURY_REALTY_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Хамовники",
    address: "1-й Зачатьевский переулок, 8",
    type: "luxury_real_estate",
    scale: "corporate",
    name: "Девелоперская компания Красная Линия",
    brand: "Khamovniki Development",
    buyPrice: 2400000,
    dailyRevenue: 56000,
    dailyExpenses: 38000,
    condition: 93,
    staffSlots: 60,
    risk: 11,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_SBER_TOWER_STAKE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Кутузовский проспект, 32",
    type: "corporate_tower",
    scale: "corporate",
    name: "Сбер Башня",
    brand: "Сбер",
    buyPrice: 3200000,
    dailyRevenue: 74000,
    dailyExpenses: 51000,
    condition: 95,
    staffSlots: 90,
    risk: 6,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_ALFA_OFFICE_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Каланчёвская улица, 27",
    type: "bank_office",
    scale: "corporate",
    name: "Альфа-Банк Центр",
    brand: "Альфа-Банк",
    buyPrice: 2100000,
    dailyRevenue: 49000,
    dailyExpenses: 33500,
    condition: 90,
    staffSlots: 55,
    risk: 7,
  },
  {
    id: "BUS_RU_MOS_PRESNYA_CORPORATE_HOLDING_001",
    countryId: "COUNTRY_RUSSIA",
    cityId: "CITY_RU_NORTH_DISTRICT",
    district: "Пресненский",
    address: "Пресненская набережная, 12",
    type: "holding_company",
    scale: "corporate",
    name: "Московский городской холдинг",
    brand: "Moscow Holding",
    buyPrice: 5000000,
    dailyRevenue: 118000,
    dailyExpenses: 82000,
    condition: 90,
    staffSlots: 120,
    risk: 10,
  },
].map((business) => ({
  ...business,
  imagePath: `${BUSINESS_ASSET_BASE}/${business.id}.jpg`,
  thumbnailPath: `${BUSINESS_ASSET_BASE}/${business.id}_thumb.jpg`,
}));

export function getBusinessTemplate(businessId) {
  return BUSINESS_TEMPLATES.find((business) => business.id === businessId) ?? null;
}

export function getBusinessTemplates(businessIds = null) {
  const ids = Array.isArray(businessIds) ? new Set(businessIds) : null;
  return BUSINESS_TEMPLATES.filter((business) => !ids || ids.has(business.id));
}
