const BASE_INTERNATIONAL_BUSINESS_TEMPLATES = [
  { id: "BUS_MO_MACAU_001", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "Cotai", address: "Local block 1", type: "international_asset", scale: "micro", name: "Taipa Snack Bar", brand: "Macau Commerce", buyPrice: 8000, dailyRevenue: 360, dailyExpenses: 180, condition: 58, staffSlots: 3, risk: 9 },
  { id: "BUS_MO_MACAU_002", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "Old Macau", address: "Local block 2", type: "international_asset", scale: "small", name: "Cotai Shuttle Service", brand: "Macau Commerce", buyPrice: 14000, dailyRevenue: 620, dailyExpenses: 310, condition: 61, staffSlots: 5, risk: 10 },
  { id: "BUS_MO_MACAU_003", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "NAPE", address: "Local block 3", type: "international_asset", scale: "small", name: "Casino Staff Canteen", brand: "Macau Commerce", buyPrice: 26000, dailyRevenue: 980, dailyExpenses: 520, condition: 64, staffSlots: 7, risk: 11 },
  { id: "BUS_MO_MACAU_004", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "Taipa", address: "Local block 4", type: "international_asset", scale: "medium", name: "VIP Tea Lounge", brand: "Macau Commerce", buyPrice: 42000, dailyRevenue: 1500, dailyExpenses: 840, condition: 67, staffSlots: 9, risk: 12 },
  { id: "BUS_MO_MACAU_005", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "Cotai", address: "Local block 5", type: "international_asset", scale: "medium", name: "Junket Office Stake", brand: "Macau Commerce", buyPrice: 78000, dailyRevenue: 2600, dailyExpenses: 1550, condition: 70, staffSlots: 11, risk: 13 },
  { id: "BUS_MO_MACAU_006", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "Old Macau", address: "Local block 6", type: "international_asset", scale: "upper_medium", name: "Luxury Watch Boutique", brand: "Macau Commerce", buyPrice: 130000, dailyRevenue: 4100, dailyExpenses: 2600, condition: 73, staffSlots: 13, risk: 14 },
  { id: "BUS_MO_MACAU_007", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "NAPE", address: "Local block 7", type: "international_asset", scale: "upper_medium", name: "Premium Hotel Floor", brand: "Macau Commerce", buyPrice: 220000, dailyRevenue: 6900, dailyExpenses: 4500, condition: 76, staffSlots: 15, risk: 15 },
  { id: "BUS_MO_MACAU_008", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_MO_MACAU_001", district: "Taipa", address: "Local block 8", type: "international_asset", scale: "large", name: "High Roller Concierge", brand: "Macau Commerce", buyPrice: 380000, dailyRevenue: 11800, dailyExpenses: 7900, condition: 79, staffSlots: 17, risk: 16 },
  { id: "BUS_HK_HONG_KONG_001", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Kowloon", address: "Local block 1", type: "international_asset", scale: "micro", name: "Kowloon Noodle Shop", brand: "Hong Kong Commerce", buyPrice: 8000, dailyRevenue: 360, dailyExpenses: 180, condition: 58, staffSlots: 3, risk: 9 },
  { id: "BUS_HK_HONG_KONG_002", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Tsim Sha Tsui", address: "Local block 2", type: "international_asset", scale: "small", name: "Central Coffee Bar", brand: "Hong Kong Commerce", buyPrice: 14000, dailyRevenue: 620, dailyExpenses: 310, condition: 61, staffSlots: 5, risk: 10 },
  { id: "BUS_HK_HONG_KONG_003", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Victoria Peak", address: "Local block 3", type: "international_asset", scale: "small", name: "Harbour Delivery Service", brand: "Hong Kong Commerce", buyPrice: 26000, dailyRevenue: 980, dailyExpenses: 520, condition: 64, staffSlots: 7, risk: 11 },
  { id: "BUS_HK_HONG_KONG_004", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Central", address: "Local block 4", type: "international_asset", scale: "medium", name: "Office Cleaning Company", brand: "Hong Kong Commerce", buyPrice: 42000, dailyRevenue: 1500, dailyExpenses: 840, condition: 67, staffSlots: 9, risk: 12 },
  { id: "BUS_HK_HONG_KONG_005", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Kowloon", address: "Local block 5", type: "international_asset", scale: "medium", name: "Finance Worker Lunch Spot", brand: "Hong Kong Commerce", buyPrice: 78000, dailyRevenue: 2600, dailyExpenses: 1550, condition: 70, staffSlots: 11, risk: 13 },
  { id: "BUS_HK_HONG_KONG_006", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Tsim Sha Tsui", address: "Local block 6", type: "international_asset", scale: "upper_medium", name: "Private Banker Lounge", brand: "Hong Kong Commerce", buyPrice: 130000, dailyRevenue: 4100, dailyExpenses: 2600, condition: 73, staffSlots: 13, risk: 14 },
  { id: "BUS_HK_HONG_KONG_007", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Victoria Peak", address: "Local block 7", type: "international_asset", scale: "upper_medium", name: "Luxury Tower Office", brand: "Hong Kong Commerce", buyPrice: 220000, dailyRevenue: 6900, dailyExpenses: 4500, condition: 76, staffSlots: 15, risk: 15 },
  { id: "BUS_HK_HONG_KONG_008", countryId: "COUNTRY_GREATER_CHINA", cityId: "CITY_HK_HONG_KONG_001", district: "Central", address: "Local block 8", type: "international_asset", scale: "large", name: "Cross-Border Poker Connector", brand: "Hong Kong Commerce", buyPrice: 380000, dailyRevenue: 11800, dailyExpenses: 7900, condition: 79, staffSlots: 17, risk: 16 },
  { id: "BUS_US_LA_001", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Hollywood", address: "Local block 1", type: "international_asset", scale: "micro", name: "Taco Stand", brand: "Los Angeles Commerce", buyPrice: 8000, dailyRevenue: 360, dailyExpenses: 180, condition: 58, staffSlots: 3, risk: 9 },
  { id: "BUS_US_LA_002", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Melrose", address: "Local block 2", type: "international_asset", scale: "small", name: "Gym Juice Bar", brand: "Los Angeles Commerce", buyPrice: 14000, dailyRevenue: 620, dailyExpenses: 310, condition: 61, staffSlots: 5, risk: 10 },
  { id: "BUS_US_LA_003", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Santa Monica", address: "Local block 3", type: "international_asset", scale: "small", name: "Studio Catering Van", brand: "Los Angeles Commerce", buyPrice: 26000, dailyRevenue: 980, dailyExpenses: 520, condition: 64, staffSlots: 7, risk: 11 },
  { id: "BUS_US_LA_004", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Downtown LA", address: "Local block 4", type: "international_asset", scale: "medium", name: "Valet Parking Crew", brand: "Los Angeles Commerce", buyPrice: 42000, dailyRevenue: 1500, dailyExpenses: 840, condition: 67, staffSlots: 9, risk: 12 },
  { id: "BUS_US_LA_005", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Hollywood", address: "Local block 5", type: "international_asset", scale: "medium", name: "Influencer Cafe", brand: "Los Angeles Commerce", buyPrice: 78000, dailyRevenue: 2600, dailyExpenses: 1550, condition: 70, staffSlots: 11, risk: 13 },
  { id: "BUS_US_LA_006", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Melrose", address: "Local block 6", type: "international_asset", scale: "upper_medium", name: "Private Mansion Bar", brand: "Los Angeles Commerce", buyPrice: 130000, dailyRevenue: 4100, dailyExpenses: 2600, condition: 73, staffSlots: 13, risk: 14 },
  { id: "BUS_US_LA_007", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Santa Monica", address: "Local block 7", type: "international_asset", scale: "upper_medium", name: "Hollywood Event Agency", brand: "Los Angeles Commerce", buyPrice: 220000, dailyRevenue: 6900, dailyExpenses: 4500, condition: 76, staffSlots: 15, risk: 15 },
  { id: "BUS_US_LA_008", countryId: "COUNTRY_USA", cityId: "CITY_US_LA_001", district: "Downtown LA", address: "Local block 8", type: "international_asset", scale: "large", name: "Athlete Lounge Stake", brand: "Los Angeles Commerce", buyPrice: 380000, dailyRevenue: 11800, dailyExpenses: 7900, condition: 79, staffSlots: 17, risk: 16 },
  { id: "BUS_US_LV_001", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "Old Vegas", address: "Local block 1", type: "international_asset", scale: "micro", name: "Poker Snack Counter", brand: "Las Vegas Commerce", buyPrice: 8000, dailyRevenue: 360, dailyExpenses: 180, condition: 58, staffSlots: 3, risk: 9 },
  { id: "BUS_US_LV_002", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "Downtown Vegas", address: "Local block 2", type: "international_asset", scale: "small", name: "Dealer Training School", brand: "Las Vegas Commerce", buyPrice: 14000, dailyRevenue: 620, dailyExpenses: 310, condition: 61, staffSlots: 5, risk: 10 },
  { id: "BUS_US_LV_003", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "Paradise", address: "Local block 3", type: "international_asset", scale: "small", name: "Casino Shuttle Company", brand: "Las Vegas Commerce", buyPrice: 26000, dailyRevenue: 980, dailyExpenses: 520, condition: 64, staffSlots: 7, risk: 11 },
  { id: "BUS_US_LV_004", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "The Strip", address: "Local block 4", type: "international_asset", scale: "medium", name: "Tournament Hostel", brand: "Las Vegas Commerce", buyPrice: 42000, dailyRevenue: 1500, dailyExpenses: 840, condition: 67, staffSlots: 9, risk: 12 },
  { id: "BUS_US_LV_005", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "Old Vegas", address: "Local block 5", type: "international_asset", scale: "medium", name: "Side Room Bar", brand: "Las Vegas Commerce", buyPrice: 78000, dailyRevenue: 2600, dailyExpenses: 1550, condition: 70, staffSlots: 11, risk: 13 },
  { id: "BUS_US_LV_006", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "Downtown Vegas", address: "Local block 6", type: "international_asset", scale: "upper_medium", name: "Old Vegas Motel", brand: "Las Vegas Commerce", buyPrice: 130000, dailyRevenue: 4100, dailyExpenses: 2600, condition: 73, staffSlots: 13, risk: 14 },
  { id: "BUS_US_LV_007", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "Paradise", address: "Local block 7", type: "international_asset", scale: "upper_medium", name: "Private Table Service", brand: "Las Vegas Commerce", buyPrice: 220000, dailyRevenue: 6900, dailyExpenses: 4500, condition: 76, staffSlots: 15, risk: 15 },
  { id: "BUS_US_LV_008", countryId: "COUNTRY_USA", cityId: "CITY_US_LAS_VEGAS_001", district: "The Strip", address: "Local block 8", type: "international_asset", scale: "large", name: "High Roller Suite Stake", brand: "Las Vegas Commerce", buyPrice: 380000, dailyRevenue: 11800, dailyExpenses: 7900, condition: 79, staffSlots: 17, risk: 16 },
  { id: "BUS_JP_TOKYO_001", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Akihabara", address: "Local block 1", type: "international_asset", scale: "micro", name: "Ramen Counter", brand: "Tokyo Commerce", buyPrice: 8000, dailyRevenue: 360, dailyExpenses: 180, condition: 58, staffSlots: 3, risk: 9 },
  { id: "BUS_JP_TOKYO_002", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Ginza", address: "Local block 2", type: "international_asset", scale: "small", name: "Convenience Franchise", brand: "Tokyo Commerce", buyPrice: 14000, dailyRevenue: 620, dailyExpenses: 310, condition: 61, staffSlots: 5, risk: 10 },
  { id: "BUS_JP_TOKYO_003", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Shibuya", address: "Local block 3", type: "international_asset", scale: "small", name: "Capsule Hotel Floor", brand: "Tokyo Commerce", buyPrice: 26000, dailyRevenue: 980, dailyExpenses: 520, condition: 64, staffSlots: 7, risk: 11 },
  { id: "BUS_JP_TOKYO_004", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Shinjuku", address: "Local block 4", type: "international_asset", scale: "medium", name: "Office Bento Service", brand: "Tokyo Commerce", buyPrice: 42000, dailyRevenue: 1500, dailyExpenses: 840, condition: 67, staffSlots: 9, risk: 12 },
  { id: "BUS_JP_TOKYO_005", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Akihabara", address: "Local block 5", type: "international_asset", scale: "medium", name: "Private Study Cafe", brand: "Tokyo Commerce", buyPrice: 78000, dailyRevenue: 2600, dailyExpenses: 1550, condition: 70, staffSlots: 11, risk: 13 },
  { id: "BUS_JP_TOKYO_006", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Ginza", address: "Local block 6", type: "international_asset", scale: "upper_medium", name: "Ginza Watch Dealer", brand: "Tokyo Commerce", buyPrice: 130000, dailyRevenue: 4100, dailyExpenses: 2600, condition: 73, staffSlots: 13, risk: 14 },
  { id: "BUS_JP_TOKYO_007", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Shibuya", address: "Local block 7", type: "international_asset", scale: "upper_medium", name: "Corporate Lounge", brand: "Tokyo Commerce", buyPrice: 220000, dailyRevenue: 6900, dailyExpenses: 4500, condition: 76, staffSlots: 15, risk: 15 },
  { id: "BUS_JP_TOKYO_008", countryId: "COUNTRY_JAPAN", cityId: "CITY_JP_TOKYO_001", district: "Shinjuku", address: "Local block 8", type: "international_asset", scale: "large", name: "High Limit Quiet Room Stake", brand: "Tokyo Commerce", buyPrice: 380000, dailyRevenue: 11800, dailyExpenses: 7900, condition: 79, staffSlots: 17, risk: 16 }
];


const CITY_FILL_BUSINESS_TEMPLATES = [
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_001",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Москва Business 1",
    "brand": "Москва Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_002",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Москва Business 2",
    "brand": "Москва Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_003",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Москва Business 3",
    "brand": "Москва Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_004",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Москва Business 4",
    "brand": "Москва Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_005",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Москва Business 5",
    "brand": "Москва Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_006",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Москва Business 6",
    "brand": "Москва Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_007",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Москва Business 7",
    "brand": "Москва Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_RU_NORTH_DISTRICT_008",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_NORTH_DISTRICT",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Москва Business 8",
    "brand": "Москва Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_001",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Санкт-Петербург Business 1",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_002",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Санкт-Петербург Business 2",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_003",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Санкт-Петербург Business 3",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_004",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Санкт-Петербург Business 4",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_005",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Санкт-Петербург Business 5",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_006",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Санкт-Петербург Business 6",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_007",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Санкт-Петербург Business 7",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_RU_SAINT_PETERSBURG_001_008",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SAINT_PETERSBURG_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Санкт-Петербург Business 8",
    "brand": "Санкт-Петербург Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_001",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Сочи Business 1",
    "brand": "Сочи Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_002",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Сочи Business 2",
    "brand": "Сочи Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_003",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Сочи Business 3",
    "brand": "Сочи Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_004",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Сочи Business 4",
    "brand": "Сочи Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_005",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Сочи Business 5",
    "brand": "Сочи Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_006",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Сочи Business 6",
    "brand": "Сочи Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_007",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Сочи Business 7",
    "brand": "Сочи Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_RU_SOCHI_001_008",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_SOCHI_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Сочи Business 8",
    "brand": "Сочи Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_001",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Владивосток Business 1",
    "brand": "Владивосток Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_002",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Владивосток Business 2",
    "brand": "Владивосток Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_003",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Владивосток Business 3",
    "brand": "Владивосток Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_004",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Владивосток Business 4",
    "brand": "Владивосток Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_005",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Владивосток Business 5",
    "brand": "Владивосток Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_006",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Владивосток Business 6",
    "brand": "Владивосток Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_007",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Владивосток Business 7",
    "brand": "Владивосток Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_RU_VLADIVOSTOK_001_008",
    "countryId": "COUNTRY_RUSSIA",
    "cityId": "CITY_RU_VLADIVOSTOK_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Владивосток Business 8",
    "brand": "Владивосток Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_US_LA_001_001",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Los Angeles Business 1",
    "brand": "Los Angeles Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_US_LA_001_002",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Los Angeles Business 2",
    "brand": "Los Angeles Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_US_LA_001_003",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Los Angeles Business 3",
    "brand": "Los Angeles Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_US_LA_001_004",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Los Angeles Business 4",
    "brand": "Los Angeles Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_US_LA_001_005",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Los Angeles Business 5",
    "brand": "Los Angeles Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_US_LA_001_006",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Los Angeles Business 6",
    "brand": "Los Angeles Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_US_LA_001_007",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Los Angeles Business 7",
    "brand": "Los Angeles Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_US_LA_001_008",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LA_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Los Angeles Business 8",
    "brand": "Los Angeles Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_001",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Las Vegas Business 1",
    "brand": "Las Vegas Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_002",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Las Vegas Business 2",
    "brand": "Las Vegas Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_003",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Las Vegas Business 3",
    "brand": "Las Vegas Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_004",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Las Vegas Business 4",
    "brand": "Las Vegas Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_005",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Las Vegas Business 5",
    "brand": "Las Vegas Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_006",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Las Vegas Business 6",
    "brand": "Las Vegas Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_007",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Las Vegas Business 7",
    "brand": "Las Vegas Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_US_LAS_VEGAS_001_008",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_LAS_VEGAS_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Las Vegas Business 8",
    "brand": "Las Vegas Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_001",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "New York Business 1",
    "brand": "New York Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_002",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "New York Business 2",
    "brand": "New York Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_003",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "New York Business 3",
    "brand": "New York Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_004",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "New York Business 4",
    "brand": "New York Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_005",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "New York Business 5",
    "brand": "New York Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_006",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "New York Business 6",
    "brand": "New York Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_007",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "New York Business 7",
    "brand": "New York Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_US_NEW_YORK_001_008",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_NEW_YORK_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "New York Business 8",
    "brand": "New York Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_001",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Miami Business 1",
    "brand": "Miami Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_002",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Miami Business 2",
    "brand": "Miami Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_003",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Miami Business 3",
    "brand": "Miami Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_004",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Miami Business 4",
    "brand": "Miami Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_005",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Miami Business 5",
    "brand": "Miami Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_006",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Miami Business 6",
    "brand": "Miami Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_007",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Miami Business 7",
    "brand": "Miami Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_US_MIAMI_001_008",
    "countryId": "COUNTRY_USA",
    "cityId": "CITY_US_MIAMI_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Miami Business 8",
    "brand": "Miami Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_001",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Macau Business 1",
    "brand": "Macau Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_002",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Macau Business 2",
    "brand": "Macau Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_003",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Macau Business 3",
    "brand": "Macau Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_004",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Macau Business 4",
    "brand": "Macau Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_005",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Macau Business 5",
    "brand": "Macau Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_006",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Macau Business 6",
    "brand": "Macau Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_007",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Macau Business 7",
    "brand": "Macau Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_MO_MACAU_001_008",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_MO_MACAU_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Macau Business 8",
    "brand": "Macau Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_001",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Hong Kong Business 1",
    "brand": "Hong Kong Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_002",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Hong Kong Business 2",
    "brand": "Hong Kong Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_003",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Hong Kong Business 3",
    "brand": "Hong Kong Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_004",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Hong Kong Business 4",
    "brand": "Hong Kong Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_005",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Hong Kong Business 5",
    "brand": "Hong Kong Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_006",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Hong Kong Business 6",
    "brand": "Hong Kong Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_007",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Hong Kong Business 7",
    "brand": "Hong Kong Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_HK_HONG_KONG_001_008",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_HK_HONG_KONG_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Hong Kong Business 8",
    "brand": "Hong Kong Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_001",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Shanghai Business 1",
    "brand": "Shanghai Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_002",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Shanghai Business 2",
    "brand": "Shanghai Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_003",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Shanghai Business 3",
    "brand": "Shanghai Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_004",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Shanghai Business 4",
    "brand": "Shanghai Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_005",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Shanghai Business 5",
    "brand": "Shanghai Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_006",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Shanghai Business 6",
    "brand": "Shanghai Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_007",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Shanghai Business 7",
    "brand": "Shanghai Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_CN_SHANGHAI_001_008",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHANGHAI_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Shanghai Business 8",
    "brand": "Shanghai Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_001",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Shenzhen Business 1",
    "brand": "Shenzhen Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_002",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Shenzhen Business 2",
    "brand": "Shenzhen Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_003",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Shenzhen Business 3",
    "brand": "Shenzhen Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_004",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Shenzhen Business 4",
    "brand": "Shenzhen Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_005",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Shenzhen Business 5",
    "brand": "Shenzhen Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_006",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Shenzhen Business 6",
    "brand": "Shenzhen Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_007",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Shenzhen Business 7",
    "brand": "Shenzhen Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_CN_SHENZHEN_001_008",
    "countryId": "COUNTRY_GREATER_CHINA",
    "cityId": "CITY_CN_SHENZHEN_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Shenzhen Business 8",
    "brand": "Shenzhen Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_001",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Tokyo Business 1",
    "brand": "Tokyo Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_002",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Tokyo Business 2",
    "brand": "Tokyo Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_003",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Tokyo Business 3",
    "brand": "Tokyo Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_004",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Tokyo Business 4",
    "brand": "Tokyo Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_005",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Tokyo Business 5",
    "brand": "Tokyo Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_006",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Tokyo Business 6",
    "brand": "Tokyo Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_007",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Tokyo Business 7",
    "brand": "Tokyo Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_JP_TOKYO_001_008",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_TOKYO_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Tokyo Business 8",
    "brand": "Tokyo Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_001",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Osaka Business 1",
    "brand": "Osaka Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_002",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Osaka Business 2",
    "brand": "Osaka Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_003",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Osaka Business 3",
    "brand": "Osaka Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_004",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Osaka Business 4",
    "brand": "Osaka Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_005",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Osaka Business 5",
    "brand": "Osaka Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_006",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Osaka Business 6",
    "brand": "Osaka Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_007",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Osaka Business 7",
    "brand": "Osaka Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_JP_OSAKA_001_008",
    "countryId": "COUNTRY_JAPAN",
    "cityId": "CITY_JP_OSAKA_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Osaka Business 8",
    "brand": "Osaka Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_001",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Seoul Business 1",
    "brand": "Seoul Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_002",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Seoul Business 2",
    "brand": "Seoul Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_003",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Seoul Business 3",
    "brand": "Seoul Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_004",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Seoul Business 4",
    "brand": "Seoul Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_005",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Seoul Business 5",
    "brand": "Seoul Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_006",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Seoul Business 6",
    "brand": "Seoul Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_007",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Seoul Business 7",
    "brand": "Seoul Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_KR_SEOUL_001_008",
    "countryId": "COUNTRY_SOUTH_KOREA",
    "cityId": "CITY_KR_SEOUL_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Seoul Business 8",
    "brand": "Seoul Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_001",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "London Business 1",
    "brand": "London Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_002",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "London Business 2",
    "brand": "London Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_003",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "London Business 3",
    "brand": "London Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_004",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "London Business 4",
    "brand": "London Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_005",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "London Business 5",
    "brand": "London Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_006",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "London Business 6",
    "brand": "London Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_007",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "London Business 7",
    "brand": "London Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_UK_LONDON_001_008",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_LONDON_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "London Business 8",
    "brand": "London Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_001",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Manchester Business 1",
    "brand": "Manchester Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_002",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Manchester Business 2",
    "brand": "Manchester Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_003",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Manchester Business 3",
    "brand": "Manchester Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_004",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Manchester Business 4",
    "brand": "Manchester Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_005",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Manchester Business 5",
    "brand": "Manchester Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_006",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Manchester Business 6",
    "brand": "Manchester Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_007",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Manchester Business 7",
    "brand": "Manchester Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_UK_MANCHESTER_001_008",
    "countryId": "COUNTRY_UK",
    "cityId": "CITY_UK_MANCHESTER_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Manchester Business 8",
    "brand": "Manchester Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_001",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Paris Business 1",
    "brand": "Paris Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_002",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Paris Business 2",
    "brand": "Paris Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_003",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Paris Business 3",
    "brand": "Paris Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_004",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Paris Business 4",
    "brand": "Paris Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_005",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Paris Business 5",
    "brand": "Paris Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_006",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Paris Business 6",
    "brand": "Paris Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_007",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Paris Business 7",
    "brand": "Paris Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_FR_PARIS_001_008",
    "countryId": "COUNTRY_FRANCE",
    "cityId": "CITY_FR_PARIS_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Paris Business 8",
    "brand": "Paris Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_001",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Monaco Business 1",
    "brand": "Monaco Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_002",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Monaco Business 2",
    "brand": "Monaco Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_003",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Monaco Business 3",
    "brand": "Monaco Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_004",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Monaco Business 4",
    "brand": "Monaco Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_005",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Monaco Business 5",
    "brand": "Monaco Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_006",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Monaco Business 6",
    "brand": "Monaco Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_007",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Monaco Business 7",
    "brand": "Monaco Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_MC_MONACO_001_008",
    "countryId": "COUNTRY_MONACO",
    "cityId": "CITY_MC_MONACO_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Monaco Business 8",
    "brand": "Monaco Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_001",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Berlin Business 1",
    "brand": "Berlin Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_002",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Berlin Business 2",
    "brand": "Berlin Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_003",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Berlin Business 3",
    "brand": "Berlin Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_004",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Berlin Business 4",
    "brand": "Berlin Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_005",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Berlin Business 5",
    "brand": "Berlin Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_006",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Berlin Business 6",
    "brand": "Berlin Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_007",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Berlin Business 7",
    "brand": "Berlin Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_DE_BERLIN_001_008",
    "countryId": "COUNTRY_GERMANY",
    "cityId": "CITY_DE_BERLIN_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Berlin Business 8",
    "brand": "Berlin Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_001",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 1",
    "type": "city_fill_asset",
    "scale": "micro",
    "name": "Barcelona Business 1",
    "brand": "Barcelona Commerce",
    "buyPrice": 8000,
    "dailyRevenue": 360,
    "dailyExpenses": 180,
    "condition": 58,
    "staffSlots": 3,
    "risk": 9
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_002",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 2",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Barcelona Business 2",
    "brand": "Barcelona Commerce",
    "buyPrice": 14000,
    "dailyRevenue": 620,
    "dailyExpenses": 310,
    "condition": 61,
    "staffSlots": 5,
    "risk": 10
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_003",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 3",
    "type": "city_fill_asset",
    "scale": "small",
    "name": "Barcelona Business 3",
    "brand": "Barcelona Commerce",
    "buyPrice": 26000,
    "dailyRevenue": 980,
    "dailyExpenses": 520,
    "condition": 64,
    "staffSlots": 7,
    "risk": 11
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_004",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 4",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Barcelona Business 4",
    "brand": "Barcelona Commerce",
    "buyPrice": 42000,
    "dailyRevenue": 1500,
    "dailyExpenses": 840,
    "condition": 67,
    "staffSlots": 9,
    "risk": 12
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_005",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 5",
    "type": "city_fill_asset",
    "scale": "medium",
    "name": "Barcelona Business 5",
    "brand": "Barcelona Commerce",
    "buyPrice": 78000,
    "dailyRevenue": 2600,
    "dailyExpenses": 1550,
    "condition": 70,
    "staffSlots": 11,
    "risk": 13
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_006",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 6",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Barcelona Business 6",
    "brand": "Barcelona Commerce",
    "buyPrice": 130000,
    "dailyRevenue": 4100,
    "dailyExpenses": 2600,
    "condition": 73,
    "staffSlots": 13,
    "risk": 14
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_007",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 7",
    "type": "city_fill_asset",
    "scale": "upper_medium",
    "name": "Barcelona Business 7",
    "brand": "Barcelona Commerce",
    "buyPrice": 220000,
    "dailyRevenue": 6900,
    "dailyExpenses": 4500,
    "condition": 76,
    "staffSlots": 15,
    "risk": 15
  },
  {
    "id": "BUS_FILL_ES_BARCELONA_001_008",
    "countryId": "COUNTRY_SPAIN",
    "cityId": "CITY_ES_BARCELONA_001",
    "district": "Center",
    "address": "Business block 8",
    "type": "city_fill_asset",
    "scale": "large",
    "name": "Barcelona Business 8",
    "brand": "Barcelona Commerce",
    "buyPrice": 380000,
    "dailyRevenue": 11800,
    "dailyExpenses": 7900,
    "condition": 79,
    "staffSlots": 17,
    "risk": 16
  }
];

export const INTERNATIONAL_BUSINESS_TEMPLATES = [...BASE_INTERNATIONAL_BUSINESS_TEMPLATES, ...CITY_FILL_BUSINESS_TEMPLATES];
