export const LIFE_LIMITS = {
  maxNeed: 100,
  maxFocus: 3,
  actionsPerDay: 6,
  rentIntervalDays: 7,
};

export const LIFE_ITEMS = [
  { id: "ITEM_WATER_BOTTLE", name: "Вода 0.5", type: "drink", price: 2, quality: "basic", venueTags: ["grocery", "night"], effect: { thirst: 30 }, imagePath: "./assets/commerce/items/ITEM_WATER_BOTTLE.jpg" },
  { id: "ITEM_WATER_LITER", name: "Вода 1.5", type: "drink", price: 3, quality: "basic", venueTags: ["grocery"], effect: { thirst: 45 }, imagePath: "./assets/commerce/items/ITEM_WATER_LITER.jpg" },
  { id: "ITEM_MINERAL_WATER", name: "Минеральная вода", type: "drink", price: 4, quality: "standard", venueTags: ["grocery", "premium"], effect: { thirst: 40, stress: -1 }, imagePath: "./assets/commerce/items/ITEM_MINERAL_WATER.jpg" },
  { id: "ITEM_COLA", name: "Кола", type: "drink", price: 4, quality: "basic", venueTags: ["grocery", "fast_food"], effect: { thirst: 22, energy: 4, stress: 1 }, imagePath: "./assets/commerce/items/ITEM_COLA.jpg" },
  { id: "ITEM_KVAS", name: "Квас", type: "drink", price: 3, quality: "basic", venueTags: ["grocery", "russian"], effect: { thirst: 28, hunger: 3 }, imagePath: "./assets/commerce/items/ITEM_KVAS.jpg" },
  { id: "ITEM_MORS", name: "Морс", type: "drink", price: 3, quality: "standard", venueTags: ["grocery", "russian"], effect: { thirst: 25, stress: -1 }, imagePath: "./assets/commerce/items/ITEM_MORS.jpg" },
  { id: "ITEM_TEA_BOTTLE", name: "Холодный чай", type: "drink", price: 4, quality: "standard", venueTags: ["grocery"], effect: { thirst: 25, energy: 3 }, imagePath: "./assets/commerce/items/ITEM_TEA_BOTTLE.jpg" },
  { id: "ITEM_COFFEE_CAN", name: "Кофе в банке", type: "drink", price: 4, quality: "basic", venueTags: ["grocery", "night"], effect: { energy: 10, stress: 3, thirst: 4 }, imagePath: "./assets/commerce/items/ITEM_COFFEE_CAN.jpg" },
  { id: "ITEM_ENERGY_DRINK", name: "Энергетик", type: "drink", price: 5, quality: "basic", venueTags: ["grocery", "night"], effect: { thirst: 15, energy: 15, stress: 5 }, imagePath: "./assets/commerce/items/ITEM_ENERGY_DRINK.jpg" },
  { id: "ITEM_PREMIUM_ENERGY", name: "Премиум энергетик", type: "drink", price: 8, quality: "standard", venueTags: ["premium", "night"], effect: { thirst: 18, energy: 22, stress: 6 }, imagePath: "./assets/commerce/items/ITEM_PREMIUM_ENERGY.jpg" },
  { id: "ITEM_BANANA", name: "Банан", type: "food", price: 2, quality: "basic", venueTags: ["grocery"], effect: { hunger: 12, energy: 3 }, imagePath: "./assets/commerce/items/ITEM_BANANA.jpg" },
  { id: "ITEM_APPLE", name: "Яблоко", type: "food", price: 2, quality: "basic", venueTags: ["grocery"], effect: { hunger: 10, thirst: 3 }, imagePath: "./assets/commerce/items/ITEM_APPLE.jpg" },
  { id: "ITEM_YOGURT", name: "Йогурт", type: "food", price: 4, quality: "standard", venueTags: ["grocery", "healthy"], effect: { hunger: 18, stress: -1 }, imagePath: "./assets/commerce/items/ITEM_YOGURT.jpg" },
  { id: "ITEM_PROTEIN_BAR", name: "Протеиновый батончик", type: "food", price: 6, quality: "standard", venueTags: ["grocery", "healthy"], effect: { hunger: 24, energy: 6 }, imagePath: "./assets/commerce/items/ITEM_PROTEIN_BAR.jpg" },
  { id: "ITEM_CHOCOLATE_BAR", name: "Шоколадный батончик", type: "dessert", price: 3, quality: "basic", venueTags: ["grocery", "night"], effect: { hunger: 14, energy: 5, stress: -1 }, imagePath: "./assets/commerce/items/ITEM_CHOCOLATE_BAR.jpg" },
  { id: "ITEM_CHIPS", name: "Чипсы", type: "snack", price: 4, quality: "basic", venueTags: ["grocery", "night"], effect: { hunger: 18, thirst: -8, stress: -1 }, imagePath: "./assets/commerce/items/ITEM_CHIPS.jpg" },
  { id: "ITEM_NUTS", name: "Орехи", type: "snack", price: 7, quality: "standard", venueTags: ["grocery", "premium"], effect: { hunger: 24, energy: 5, thirst: -3 }, imagePath: "./assets/commerce/items/ITEM_NUTS.jpg" },
  { id: "ITEM_SANDWICH", name: "Сэндвич", type: "food", price: 8, quality: "basic", venueTags: ["grocery"], effect: { hunger: 35 }, imagePath: "./assets/commerce/items/ITEM_SANDWICH.jpg" },
  { id: "ITEM_HAM_CHEESE_SANDWICH", name: "Сэндвич ветчина-сыр", type: "food", price: 10, quality: "standard", venueTags: ["grocery", "cafe"], effect: { hunger: 42 }, imagePath: "./assets/commerce/items/ITEM_HAM_CHEESE_SANDWICH.jpg" },
  { id: "ITEM_CHICKEN_WRAP", name: "Ролл с курицей", type: "food", price: 11, quality: "standard", venueTags: ["grocery", "fast_food"], effect: { hunger: 46, energy: 3 }, imagePath: "./assets/commerce/items/ITEM_CHICKEN_WRAP.jpg" },
  { id: "ITEM_READY_MEAL", name: "Готовый обед", type: "meal", price: 14, quality: "basic", venueTags: ["grocery"], effect: { hunger: 60 }, imagePath: "./assets/commerce/items/ITEM_READY_MEAL.jpg" },
  { id: "ITEM_BUCKWHEAT_CHICKEN_BOX", name: "Гречка с курицей", type: "meal", price: 13, quality: "standard", venueTags: ["grocery", "healthy"], effect: { hunger: 55, stress: -1 }, imagePath: "./assets/commerce/items/ITEM_BUCKWHEAT_CHICKEN_BOX.jpg" },
  { id: "ITEM_PLOV_BOX", name: "Плов", type: "meal", price: 15, quality: "standard", venueTags: ["grocery"], effect: { hunger: 62 }, imagePath: "./assets/commerce/items/ITEM_PLOV_BOX.jpg" },
  { id: "ITEM_PASTA_BOX", name: "Паста в контейнере", type: "meal", price: 16, quality: "standard", venueTags: ["grocery"], effect: { hunger: 58, stress: -2 }, imagePath: "./assets/commerce/items/ITEM_PASTA_BOX.jpg" },
  { id: "ITEM_SALAD_CAESAR_BOX", name: "Цезарь в контейнере", type: "meal", price: 18, quality: "premium", venueTags: ["premium", "healthy"], effect: { hunger: 45, energy: 4, stress: -4 }, imagePath: "./assets/commerce/items/ITEM_SALAD_CAESAR_BOX.jpg" },
  { id: "ITEM_SALMON_SALAD_BOX", name: "Салат с лососем", type: "meal", price: 28, quality: "premium", venueTags: ["premium", "healthy"], effect: { hunger: 48, energy: 6, stress: -8 }, imagePath: "./assets/commerce/items/ITEM_SALMON_SALAD_BOX.jpg" },
  { id: "ITEM_SOUP_BORSCH_PACK", name: "Борщ готовый", type: "meal", price: 12, quality: "standard", venueTags: ["grocery", "russian"], effect: { hunger: 38, thirst: 8, stress: -3 }, imagePath: "./assets/commerce/items/ITEM_SOUP_BORSCH_PACK.jpg" },
  { id: "ITEM_DUMPLINGS_PACK", name: "Пельмени", type: "meal", price: 11, quality: "basic", venueTags: ["grocery", "russian"], effect: { hunger: 50, thirst: -4 }, imagePath: "./assets/commerce/items/ITEM_DUMPLINGS_PACK.jpg" },
  { id: "ITEM_SYRNIKI_PACK", name: "Сырники", type: "dessert", price: 9, quality: "standard", venueTags: ["grocery", "russian"], effect: { hunger: 30, stress: -3 }, imagePath: "./assets/commerce/items/ITEM_SYRNIKI_PACK.jpg" },
  { id: "ITEM_COTTAGE_CHEESE", name: "Творог", type: "food", price: 6, quality: "standard", venueTags: ["grocery", "healthy"], effect: { hunger: 26, energy: 3 }, imagePath: "./assets/commerce/items/ITEM_COTTAGE_CHEESE.jpg" },
  { id: "ITEM_OMELET_BOX", name: "Омлет", type: "meal", price: 10, quality: "standard", venueTags: ["grocery"], effect: { hunger: 35, energy: 6 }, imagePath: "./assets/commerce/items/ITEM_OMELET_BOX.jpg" },
  { id: "ITEM_CROISSANT_PACK", name: "Круассан", type: "dessert", price: 7, quality: "premium", venueTags: ["premium", "cafe"], effect: { hunger: 20, stress: -4 }, imagePath: "./assets/commerce/items/ITEM_CROISSANT_PACK.jpg" },
  { id: "ITEM_DONUT", name: "Пончик", type: "dessert", price: 5, quality: "basic", venueTags: ["grocery", "cafe"], effect: { hunger: 20, energy: 4, stress: -2 }, imagePath: "./assets/commerce/items/ITEM_DONUT.jpg" },
  { id: "ITEM_PREMIUM_STEAK_BOX", name: "Стейк-салат готовый", type: "meal", price: 35, quality: "premium", venueTags: ["premium"], effect: { hunger: 75, energy: 8, stress: -10 }, imagePath: "./assets/commerce/items/ITEM_PREMIUM_STEAK_BOX.jpg" },

  { id: "ITEM_KEFIR", name: "Кефир", type: "drink", price: 4, quality: "standard", venueTags: ["grocery", "healthy"], effect: { thirst: 18, hunger: 10, stress: -1 }, imagePath: "./assets/commerce/items/ITEM_KEFIR.jpg" },
  { id: "ITEM_PROTEIN_SHAKE", name: "Протеиновый коктейль", type: "drink", price: 9, quality: "standard", venueTags: ["healthy", "premium"], effect: { thirst: 18, hunger: 18, energy: 8 }, imagePath: "./assets/commerce/items/ITEM_PROTEIN_SHAKE.jpg" },
  { id: "ITEM_CHICKEN_SALAD", name: "Куриный салат", type: "meal", price: 19, quality: "standard", venueTags: ["healthy"], effect: { hunger: 52, energy: 4, stress: -4 }, imagePath: "./assets/commerce/items/ITEM_CHICKEN_SALAD.jpg" },
  { id: "ITEM_SUSHI_BOX", name: "Суши-бокс", type: "meal", price: 24, quality: "premium", venueTags: ["premium"], effect: { hunger: 58, stress: -7 }, imagePath: "./assets/commerce/items/ITEM_SUSHI_BOX.jpg" },
  { id: "ITEM_CHEESECAKE", name: "Чизкейк", type: "dessert", price: 8, quality: "standard", venueTags: ["cafe", "premium"], effect: { hunger: 25, stress: -5 }, imagePath: "./assets/commerce/items/ITEM_CHEESECAKE.jpg" },
  { id: "ITEM_BLACK_CAVIAR_SNACK", name: "Икра и тосты", type: "meal", price: 95, quality: "luxury", venueTags: ["luxury"], effect: { hunger: 55, stress: -18 }, imagePath: "./assets/commerce/items/ITEM_BLACK_CAVIAR_SNACK.jpg" },
];

export const LIFE_CAFE_ORDERS = [
  { id: "CAFE_BREAKFAST", name: "Завтрак", price: 18, actionCost: 1, effect: { hunger: 70, energy: 10, stress: -5, thirst: 10 } },
  { id: "CAFE_COFFEE", name: "Кофе", price: 5, actionCost: 1, effect: { energy: 15, stress: 4, thirst: 5 } },
  { id: "CAFE_LUNCH", name: "Обед", price: 25, actionCost: 1, effect: { hunger: 90, stress: -8, thirst: 15 } },
  { id: "ORDER_TEREMOK_HAM_CHEESE_BLIN", name: "Теремок: блин ветчина-сыр", price: 7, actionCost: 1, effect: { hunger: 35, stress: -1 } },
  { id: "ORDER_TEREMOK_CHICKEN_BLIN", name: "Теремок: блин с курицей", price: 8, actionCost: 1, effect: { hunger: 40, energy: 3 } },
  { id: "ORDER_TEREMOK_SALMON_BLIN", name: "Теремок: блин с сёмгой", price: 14, actionCost: 1, effect: { hunger: 45, stress: -3 } },
  { id: "ORDER_TEREMOK_SYRNIKI", name: "Теремок: сырники", price: 6, actionCost: 1, effect: { hunger: 25, stress: -2 } },
  { id: "ORDER_TEREMOK_MORS", name: "Теремок: морс", price: 3, actionCost: 1, effect: { thirst: 25, stress: -1 } },
  { id: "ORDER_MUMU_BORSCH", name: "Му-Му: борщ", price: 8, actionCost: 1, effect: { hunger: 35, thirst: 8, stress: -3 } },
  { id: "ORDER_MUMU_CUTLET_PUREE", name: "Му-Му: котлета с пюре", price: 12, actionCost: 1, effect: { hunger: 60 } },
  { id: "ORDER_MUMU_BUCKWHEAT_CHICKEN", name: "Му-Му: гречка с курицей", price: 10, actionCost: 1, effect: { hunger: 50, energy: 3 } },
  { id: "ORDER_MUMU_OLIVIER", name: "Му-Му: оливье", price: 7, actionCost: 1, effect: { hunger: 25, stress: -1 } },
  { id: "ORDER_MUMU_COMPOT", name: "Му-Му: компот", price: 3, actionCost: 1, effect: { thirst: 25, stress: -1 } },
  { id: "ORDER_SHOKO_AMERICANO", name: "Шоколадница: американо", price: 4, actionCost: 1, effect: { energy: 8, thirst: 5 } },
  { id: "ORDER_SHOKO_CAPPUCCINO", name: "Шоколадница: капучино", price: 5, actionCost: 1, effect: { energy: 10, stress: -1, thirst: 4 } },
  { id: "ORDER_SHOKO_HOT_CHOCOLATE", name: "Шоколадница: горячий шоколад", price: 6, actionCost: 1, effect: { hunger: 8, energy: 5, stress: -5 } },
  { id: "ORDER_SHOKO_PANCAKES", name: "Шоколадница: панкейки", price: 9, actionCost: 1, effect: { hunger: 35, stress: -4 } },
  { id: "ORDER_SHOKO_CHICKEN_SANDWICH", name: "Шоколадница: сэндвич с курицей", price: 10, actionCost: 1, effect: { hunger: 45 } },
  { id: "ORDER_VKUSNO_BURGER", name: "Вкусно — и точка: бургер", price: 8, actionCost: 1, effect: { hunger: 42, thirst: -4 } },
  { id: "ORDER_VKUSNO_FRIES", name: "Вкусно — и точка: картофель", price: 4, actionCost: 1, effect: { hunger: 22, thirst: -6, stress: -1 } },
  { id: "ORDER_VKUSNO_COMBO", name: "Вкусно — и точка: комбо", price: 13, actionCost: 1, effect: { hunger: 65, thirst: 12, stress: -1 } },
  { id: "ORDER_ROSTICS_CHICKEN_BUCKET", name: "Rostic's: куриный бокс", price: 14, actionCost: 1, effect: { hunger: 70, thirst: -6 } },
  { id: "ORDER_ROSTICS_TWISTER", name: "Rostic's: твистер", price: 9, actionCost: 1, effect: { hunger: 45 } },
  { id: "ORDER_DODO_PEPPERONI", name: "Додо Пицца: пепперони", price: 16, actionCost: 1, effect: { hunger: 80, stress: -3 } },
  { id: "ORDER_DODO_CHEESE_PIZZA", name: "Додо Пицца: сырная", price: 14, actionCost: 1, effect: { hunger: 70, stress: -2 } },
  { id: "ORDER_YAKITORIYA_ROLLS", name: "Якитория: роллы", price: 18, actionCost: 1, effect: { hunger: 55, stress: -5 } },
  { id: "ORDER_YAKITORIYA_RAMEN", name: "Якитория: рамен", price: 16, actionCost: 1, effect: { hunger: 65, thirst: 8, stress: -4 } },
  { id: "ORDER_TANUKI_SET", name: "Тануки: сет", price: 26, actionCost: 1, effect: { hunger: 80, stress: -8 } },
  { id: "ORDER_COFFEEMANIA_FLAT_WHITE", name: "Кофемания: флэт уайт", price: 8, actionCost: 1, effect: { energy: 14, stress: -3, thirst: 4 } },
  { id: "ORDER_COFFEEMANIA_CROISSANT", name: "Кофемания: круассан", price: 7, actionCost: 1, effect: { hunger: 20, stress: -4 } },
  { id: "ORDER_COFFEEMANIA_SALMON_BREAKFAST", name: "Кофемания: завтрак с лососем", price: 22, actionCost: 1, effect: { hunger: 70, energy: 5, stress: -8 } },
  { id: "ORDER_COFFEEMANIA_STEAK_SALAD", name: "Кофемания: стейк-салат", price: 28, actionCost: 1, effect: { hunger: 75, stress: -10 } },
  { id: "ORDER_CHAIHONA_PLOV", name: "Чайхона №1: плов", price: 17, actionCost: 1, effect: { hunger: 75, stress: -4 } },
  { id: "ORDER_CHAIHONA_LAGMAN", name: "Чайхона №1: лагман", price: 15, actionCost: 1, effect: { hunger: 65, thirst: 6, stress: -4 } },
  { id: "ORDER_PREMIUM_TASTING", name: "Премиальный ресторан: дегустационный сет", price: 90, actionCost: 1, effect: { hunger: 90, energy: 8, stress: -22 } },
  { id: "ORDER_PREMIUM_STEAK", name: "Премиальный ресторан: стейк", price: 75, actionCost: 1, effect: { hunger: 85, stress: -16 } },
];

export const LIFE_JOBS = [
  {
    id: "JOB_DELIVERY_SHIFT",
    name: "Delivery Shift",
    pay: 80,
    actionCost: 1,
    effect: { energy: -30, hunger: -15, thirst: -20, stress: 15 },
  },
  {
    id: "JOB_WAREHOUSE_SHIFT",
    name: "Warehouse Shift",
    pay: 120,
    actionCost: 2,
    effect: { energy: -45, hunger: -25, thirst: -25, stress: 20 },
  },
  {
    id: "JOB_CAFE_HELPER",
    name: "Cafe Helper",
    pay: 60,
    actionCost: 1,
    effect: { energy: -20, hunger: 30, stress: 8, thirst: -10 },
  },
];

const HOUSING_ALIAS_IDS = {
  HOUSING_CHEAP_ROOM: "HOUSING_RU_MOS_BIRYULYOVO_ROOM_001",
  HOUSING_SMALL_STUDIO: "HOUSING_RU_MOS_NEKRASOVKA_STUDIO_001",
  HOUSING_APARTMENT: "HOUSING_RU_MOS_CHERTANOVO_1ROOM_001",
};

export const LIFE_HOUSING = [
  {
    id: "HOUSING_RU_MOS_BIRYULYOVO_ROOM_001",
    legacyIds: ["HOUSING_CHEAP_ROOM"],
    name: "Комната в Бирюлёво",
    district: "Бирюлёво Западное",
    address: "Булатниковский проезд, 6",
    rooms: 1,
    sqm: 14,
    capacity: 1,
    repair: "уставший косметический",
    tier: "outskirts_basic",
    rent: 250,
    intervalDays: 7,
    restEffect: { energy: 35, stress: -5, hunger: -6, thirst: -8 },
    purchasePrice: null,
  },
  {
    id: "HOUSING_RU_MOS_KAPOTNYA_ROOM_001",
    name: "Комната в Капотне",
    district: "Капотня",
    address: "2-й квартал Капотни, 17",
    rooms: 1,
    sqm: 12,
    capacity: 1,
    repair: "старый ремонт",
    tier: "outskirts_basic",
    rent: 300,
    intervalDays: 7,
    restEffect: { energy: 36, stress: -4, hunger: -6, thirst: -8 },
    purchasePrice: null,
  },
  {
    id: "HOUSING_RU_MOS_NEKRASOVKA_STUDIO_001",
    legacyIds: ["HOUSING_SMALL_STUDIO"],
    name: "Студия в Некрасовке",
    district: "Некрасовка",
    address: "Рождественская улица, 33",
    rooms: 1,
    sqm: 22,
    capacity: 1,
    repair: "простой ремонт от застройщика",
    tier: "budget_studio",
    rent: 500,
    intervalDays: 7,
    restEffect: { energy: 50, stress: -10, hunger: -5, thirst: -6 },
    purchasePrice: 25000,
  },
  {
    id: "HOUSING_RU_MOS_BUTOVO_STUDIO_001",
    name: "Студия в Южном Бутово",
    district: "Южное Бутово",
    address: "Скобелевская улица, 20",
    rooms: 1,
    sqm: 28,
    capacity: 1,
    repair: "аккуратный косметический",
    tier: "budget_studio",
    rent: 620,
    intervalDays: 7,
    restEffect: { energy: 53, stress: -11, hunger: -5, thirst: -6 },
    purchasePrice: 32000,
  },
  {
    id: "HOUSING_RU_MOS_CHERTANOVO_1ROOM_001",
    legacyIds: ["HOUSING_APARTMENT"],
    name: "Однушка в Чертаново",
    district: "Чертаново Центральное",
    address: "Кировоградская улица, 42",
    rooms: 1,
    sqm: 38,
    capacity: 2,
    repair: "нормальный косметический",
    tier: "standard_flat",
    rent: 900,
    intervalDays: 7,
    restEffect: { energy: 65, stress: -15, hunger: -4, thirst: -5 },
    purchasePrice: 65000,
  },
  {
    id: "HOUSING_RU_MOS_MITINO_2ROOM_001",
    name: "Двушка в Митино",
    district: "Митино",
    address: "Митинская улица, 36",
    rooms: 2,
    sqm: 52,
    capacity: 2,
    repair: "хороший косметический",
    tier: "standard_flat",
    rent: 1250,
    intervalDays: 7,
    restEffect: { energy: 70, stress: -18, hunger: -4, thirst: -5 },
    purchasePrice: 92000,
  },
  {
    id: "HOUSING_RU_MOS_DANILOVSKY_2ROOM_001",
    name: "Двушка в Даниловском",
    district: "Даниловский",
    address: "Автозаводская улица, 23",
    rooms: 2,
    sqm: 58,
    capacity: 2,
    repair: "современный ремонт",
    tier: "business_flat",
    rent: 1850,
    intervalDays: 7,
    restEffect: { energy: 76, stress: -22, hunger: -3, thirst: -4 },
    purchasePrice: 150000,
  },
  {
    id: "HOUSING_RU_MOS_PRESNYA_2ROOM_001",
    name: "Двушка на Пресне",
    district: "Пресненский",
    address: "Ходынский бульвар, 20А",
    rooms: 2,
    sqm: 64,
    capacity: 2,
    repair: "дорогой современный",
    tier: "premium_flat",
    rent: 2600,
    intervalDays: 7,
    restEffect: { energy: 82, stress: -26, hunger: -3, thirst: -4 },
    purchasePrice: 240000,
  },
  {
    id: "HOUSING_RU_MOS_KHAMOVNIKI_3ROOM_001",
    name: "Трёшка в Хамовниках",
    district: "Хамовники",
    address: "Усачёва улица, 11",
    rooms: 3,
    sqm: 92,
    capacity: 3,
    repair: "премиальный ремонт",
    tier: "elite_flat",
    rent: 4200,
    intervalDays: 7,
    restEffect: { energy: 88, stress: -32, hunger: -2, thirst: -3 },
    purchasePrice: 430000,
  },
  {
    id: "HOUSING_RU_MOS_KHAMOVNIKI_ELITE_001",
    name: "Элитная квартира в Хамовниках",
    district: "Хамовники",
    address: "1-й Зачатьевский переулок, 8",
    rooms: 4,
    sqm: 140,
    capacity: 4,
    repair: "дизайнерский ремонт",
    tier: "elite_luxury",
    rent: 7200,
    intervalDays: 7,
    restEffect: { energy: 95, stress: -40, hunger: -1, thirst: -2 },
    purchasePrice: 850000,
  },
];

export const LIFE_ASSETS = [
  {
    id: "ASSET_PHONE",
    name: "Нормальный телефон",
    price: 700,
    type: "tech",
    effect: { status: 1 },
  },
  {
    id: "ASSET_LAPTOP",
    name: "Ноутбук",
    price: 1200,
    type: "tech",
    effect: { status: 1 },
  },
  {
    id: "ASSET_WATCH",
    name: "Часы",
    price: 1500,
    type: "status",
    effect: { status: 1 },
  },
];

export const LIFE_VEHICLES = [
  { id: "VEHICLE_LADA_GRANTA", name: "Lada Granta", class: "cheap", price: 3500, upkeepPer7Days: 120, stressModifier: -2, travelEnergyCost: 6, seats: 5, effect: { stress: -2 }, imagePath: "./assets/vehicles/VEHICLE_LADA_GRANTA.jpg" },
  { id: "VEHICLE_LADA_VESTA", name: "Lada Vesta", class: "cheap", price: 5200, upkeepPer7Days: 150, stressModifier: -3, travelEnergyCost: 5, status: 2, seats: 5, effect: { stress: -3 }, imagePath: "./assets/vehicles/VEHICLE_LADA_VESTA.jpg" },
  { id: "VEHICLE_RENAULT_LOGAN", legacyIds: ["VEHICLE_OLD_CAR"], name: "Renault Logan", class: "cheap", price: 6000, upkeepPer7Days: 160, stressModifier: -4, travelEnergyCost: 5, status: 2, seats: 5, effect: { stress: -4 }, imagePath: "./assets/vehicles/VEHICLE_RENAULT_LOGAN.jpg" },
  { id: "VEHICLE_HYUNDAI_SOLARIS", name: "Hyundai Solaris", class: "cheap", price: 7500, upkeepPer7Days: 180, stressModifier: -5, travelEnergyCost: 4, status: 3, seats: 5, effect: { stress: -5 }, imagePath: "./assets/vehicles/VEHICLE_HYUNDAI_SOLARIS.jpg" },
  { id: "VEHICLE_KIA_RIO", name: "Kia Rio", class: "cheap", price: 7800, upkeepPer7Days: 180, stressModifier: -5, travelEnergyCost: 4, status: 3, seats: 5, effect: { stress: -5 }, imagePath: "./assets/vehicles/VEHICLE_KIA_RIO.jpg" },
  { id: "VEHICLE_VOLKSWAGEN_POLO", name: "Volkswagen Polo", class: "cheap", price: 8500, upkeepPer7Days: 200, stressModifier: -5, travelEnergyCost: 4, status: 3, seats: 5, effect: { stress: -5 }, imagePath: "./assets/vehicles/VEHICLE_VOLKSWAGEN_POLO.jpg" },
  { id: "VEHICLE_SKODA_RAPID", name: "Skoda Rapid", class: "cheap", price: 9000, upkeepPer7Days: 210, stressModifier: -6, travelEnergyCost: 4, status: 3, seats: 5, effect: { stress: -6 }, imagePath: "./assets/vehicles/VEHICLE_SKODA_RAPID.jpg" },
  { id: "VEHICLE_TOYOTA_CAMRY", legacyIds: ["VEHICLE_SEDAN"], name: "Toyota Camry", class: "middle", price: 18000, upkeepPer7Days: 420, stressModifier: -8, travelEnergyCost: 3, status: 5, seats: 5, effect: { stress: -8 }, imagePath: "./assets/vehicles/VEHICLE_TOYOTA_CAMRY.jpg" },
  { id: "VEHICLE_MAZDA_6", name: "Mazda 6", class: "middle", price: 17000, upkeepPer7Days: 400, stressModifier: -8, travelEnergyCost: 3, status: 5, seats: 5, effect: { stress: -8 }, imagePath: "./assets/vehicles/VEHICLE_MAZDA_6.jpg" },
  { id: "VEHICLE_KIA_K5", name: "Kia K5", class: "middle", price: 19000, upkeepPer7Days: 430, stressModifier: -9, travelEnergyCost: 3, status: 5, seats: 5, effect: { stress: -9 }, imagePath: "./assets/vehicles/VEHICLE_KIA_K5.jpg" },
  { id: "VEHICLE_HYUNDAI_SONATA", name: "Hyundai Sonata", class: "middle", price: 19500, upkeepPer7Days: 440, stressModifier: -9, travelEnergyCost: 3, status: 5, seats: 5, effect: { stress: -9 }, imagePath: "./assets/vehicles/VEHICLE_HYUNDAI_SONATA.jpg" },
  { id: "VEHICLE_HAVAL_JOLION", name: "Haval Jolion", class: "middle", price: 16000, upkeepPer7Days: 380, stressModifier: -7, travelEnergyCost: 3, status: 4, seats: 5, effect: { stress: -7 }, imagePath: "./assets/vehicles/VEHICLE_HAVAL_JOLION.jpg" },
  { id: "VEHICLE_GEELY_COOLRAY", name: "Geely Coolray", class: "middle", price: 16500, upkeepPer7Days: 390, stressModifier: -7, travelEnergyCost: 3, status: 4, seats: 5, effect: { stress: -7 }, imagePath: "./assets/vehicles/VEHICLE_GEELY_COOLRAY.jpg" },
  { id: "VEHICLE_CHERY_TIGGO_7", name: "Chery Tiggo 7 Pro", class: "middle", price: 17500, upkeepPer7Days: 410, stressModifier: -8, travelEnergyCost: 3, status: 4, seats: 5, effect: { stress: -8 }, imagePath: "./assets/vehicles/VEHICLE_CHERY_TIGGO_7.jpg" },
  { id: "VEHICLE_OMODA_C5", name: "Omoda C5", class: "middle", price: 18500, upkeepPer7Days: 420, stressModifier: -8, travelEnergyCost: 3, status: 4, seats: 5, effect: { stress: -8 }, imagePath: "./assets/vehicles/VEHICLE_OMODA_C5.jpg" },
  { id: "VEHICLE_PRADO", name: "Toyota Land Cruiser Prado", class: "business", price: 32000, upkeepPer7Days: 800, stressModifier: -11, travelEnergyCost: 2, status: 7, seats: 5, effect: { stress: -11 }, imagePath: "./assets/vehicles/VEHICLE_PRADO.jpg" },
  { id: "VEHICLE_GEELY_MONJARO", name: "Geely Monjaro", class: "business", price: 30000, upkeepPer7Days: 720, stressModifier: -10, travelEnergyCost: 2, status: 6, seats: 5, effect: { stress: -10 }, imagePath: "./assets/vehicles/VEHICLE_GEELY_MONJARO.jpg" },
  { id: "VEHICLE_TANK_300", name: "Tank 300", class: "business", price: 34000, upkeepPer7Days: 850, stressModifier: -11, travelEnergyCost: 2, status: 7, seats: 5, effect: { stress: -11 }, imagePath: "./assets/vehicles/VEHICLE_TANK_300.jpg" },
  { id: "VEHICLE_TANK_500", name: "Tank 500", class: "business", price: 47000, upkeepPer7Days: 1100, stressModifier: -13, travelEnergyCost: 2, status: 8, seats: 5, effect: { stress: -13 }, imagePath: "./assets/vehicles/VEHICLE_TANK_500.jpg" },
  { id: "VEHICLE_BMW_5", name: "BMW 5 Series", class: "business", price: 52000, upkeepPer7Days: 1300, stressModifier: -14, travelEnergyCost: 2, status: 9, seats: 5, effect: { stress: -14 }, imagePath: "./assets/vehicles/VEHICLE_BMW_5.jpg" },
  { id: "VEHICLE_MERCEDES_E", name: "Mercedes E-Class", class: "business", price: 56000, upkeepPer7Days: 1400, stressModifier: -15, travelEnergyCost: 2, status: 9, seats: 5, effect: { stress: -15 }, imagePath: "./assets/vehicles/VEHICLE_MERCEDES_E.jpg" },
  { id: "VEHICLE_AUDI_A6", name: "Audi A6", class: "business", price: 54000, upkeepPer7Days: 1350, stressModifier: -14, travelEnergyCost: 2, status: 9, seats: 5, effect: { stress: -14 }, imagePath: "./assets/vehicles/VEHICLE_AUDI_A6.jpg" },
  { id: "VEHICLE_LEXUS_RX", name: "Lexus RX", class: "business", price: 62000, upkeepPer7Days: 1500, stressModifier: -16, travelEnergyCost: 2, status: 9, seats: 5, effect: { stress: -16 }, imagePath: "./assets/vehicles/VEHICLE_LEXUS_RX.jpg" },
  { id: "VEHICLE_BMW_X5", name: "BMW X5", class: "premium", price: 78000, upkeepPer7Days: 1900, stressModifier: -18, travelEnergyCost: 11, seats: 5, effect: { stress: -18 }, imagePath: "./assets/vehicles/VEHICLE_BMW_X5.jpg" },
  { id: "VEHICLE_MERCEDES_GLE", name: "Mercedes GLE", class: "premium", price: 82000, upkeepPer7Days: 2000, stressModifier: -18, travelEnergyCost: 11, seats: 5, effect: { stress: -18 }, imagePath: "./assets/vehicles/VEHICLE_MERCEDES_GLE.jpg" },
  { id: "VEHICLE_MERCEDES_S", name: "Mercedes S-Class", class: "premium", price: 120000, upkeepPer7Days: 2800, stressModifier: -22, travelEnergyCost: 14, seats: 5, effect: { stress: -22 }, imagePath: "./assets/vehicles/VEHICLE_MERCEDES_S.jpg" },
  { id: "VEHICLE_BMW_7", name: "BMW 7 Series", class: "premium", price: 115000, upkeepPer7Days: 2700, stressModifier: -21, travelEnergyCost: 14, seats: 5, effect: { stress: -21 }, imagePath: "./assets/vehicles/VEHICLE_BMW_7.jpg" },
  { id: "VEHICLE_LEXUS_LX", name: "Lexus LX", class: "premium", price: 135000, upkeepPer7Days: 3000, stressModifier: -22, travelEnergyCost: 15, seats: 5, effect: { stress: -22 }, imagePath: "./assets/vehicles/VEHICLE_LEXUS_LX.jpg" },
  { id: "VEHICLE_PORSCHE_CAYENNE", name: "Porsche Cayenne", class: "premium", price: 150000, upkeepPer7Days: 3400, stressModifier: -24, travelEnergyCost: 16, seats: 5, effect: { stress: -24 }, imagePath: "./assets/vehicles/VEHICLE_PORSCHE_CAYENNE.jpg" },
  { id: "VEHICLE_RANGE_ROVER", name: "Range Rover", class: "luxury", price: 180000, upkeepPer7Days: 4200, stressModifier: -26, travelEnergyCost: 18, seats: 5, effect: { stress: -26 }, imagePath: "./assets/vehicles/VEHICLE_RANGE_ROVER.jpg" },
  { id: "VEHICLE_MERCEDES_G", name: "Mercedes G-Class", class: "luxury", price: 220000, upkeepPer7Days: 5000, stressModifier: -28, travelEnergyCost: 1, status: 20, seats: 5, effect: { stress: -28 }, imagePath: "./assets/vehicles/VEHICLE_MERCEDES_G.jpg" },
  { id: "VEHICLE_BENTLEY_BENTAYGA", name: "Bentley Bentayga", class: "luxury", price: 320000, upkeepPer7Days: 7200, stressModifier: -32, travelEnergyCost: 1, status: 24, seats: 5, effect: { stress: -32 }, imagePath: "./assets/vehicles/VEHICLE_BENTLEY_BENTAYGA.jpg" },
  { id: "VEHICLE_ROLLS_CULLINAN", name: "Rolls-Royce Cullinan", class: "luxury", price: 480000, upkeepPer7Days: 10000, stressModifier: -36, travelEnergyCost: 1, status: 30, seats: 5, effect: { stress: -36 }, imagePath: "./assets/vehicles/VEHICLE_ROLLS_CULLINAN.jpg" },
];

export function getLifeItem(itemId) {
  return LIFE_ITEMS.find((item) => item.id === itemId) ?? null;
}

export function getLifeCafeOrder(orderId) {
  return LIFE_CAFE_ORDERS.find((order) => order.id === orderId) ?? null;
}

export function getLifeJob(jobId) {
  return LIFE_JOBS.find((job) => job.id === jobId) ?? null;
}

export function getLifeHousing(housingId) {
  const normalizedId = HOUSING_ALIAS_IDS[housingId] ?? housingId;
  return LIFE_HOUSING.find((housing) => housing.id === normalizedId || (housing.legacyIds ?? []).includes(housingId)) ?? LIFE_HOUSING[0];
}

export function getLifeAsset(assetId) {
  return LIFE_ASSETS.find((asset) => asset.id === assetId) ?? null;
}

export function getLifeVehicle(vehicleId) {
  return LIFE_VEHICLES.find((vehicle) => vehicle.id === vehicleId || (vehicle.legacyIds ?? []).includes(vehicleId)) ?? null;
}
